In [1]:
from pydrake.all import (MathematicalProgram, DecomposeLinearExpressions, L2NormCost,
                         Binding, Cost)
import numpy as np

## Understanding DecomposeLinearExpressions()

In [27]:


prog = MathematicalProgram()

x = prog.NewContinuousVariables(3)
exprs = [x[0]*5 - x[1], x[1]*2, x[2]*3 + x[0]]
A = DecomposeLinearExpressions(exprs, x)
print(A)

[[ 5. -1.  0.]
 [ 0.  2.  0.]
 [ 1.  0.  3.]]


In [33]:

prog = MathematicalProgram()

x = prog.NewContinuousVariables(2,2)
exprs = x[0]-x[1]
A = DecomposeLinearExpressions(exprs, x.flatten())
print(A)
b = np.zeros((A.shape[0],1))
print(b)
l2_norm_cost = L2NormCost(A, b)
prog.AddCost(l2_norm_cost, x.flatten())

[[ 1.  0. -1.  0.]
 [ 0.  1.  0. -1.]]
[[0.]
 [0.]]
