In [ ]:
from pydrake.all import (MathematicalProgram, DecomposeLinearExpressions, L2NormCost,
                         Binding, Cost)
import numpy as np

## Understanding DecomposeLinearExpressions()

In [ ]:


prog = MathematicalProgram()

x = prog.NewContinuousVariables(3)
exprs = [x[0]*5 - x[1], x[1]*2, x[2]*3 + x[0]]
A = DecomposeLinearExpressions(exprs, x)
print(A)

In [ ]:

prog = MathematicalProgram()

x = prog.NewContinuousVariables(2,2)
exprs = x[0]-x[1]
A = DecomposeLinearExpressions(exprs, x.flatten())
print(A)
b = np.zeros((A.shape[0],1))
print(b)
l2_norm_cost = L2NormCost(A, b)
prog.AddCost(l2_norm_cost, x.flatten())

In [8]:
import numpy as np
from pydrake.all import (MathematicalProgram, QuadraticCost)
n = 2  # Dimension of x1 and x2
prog = MathematicalProgram()

x = prog.NewContinuousVariables(2,n).reshape(1,2*n)
I_n = np.identity(n)
Q = np.block([[I_n, -I_n], [-I_n, I_n]])
b = np.zeros((2*n,1))
c = 0
cost = QuadraticCost(Q, b, c)
prog.AddCost(cost, x.flatten())
expr = (x @ Q @ x.T).flatten()[0]
print(Q)
print(expr.Expand())


[[ 1.  0. -1. -0.]
 [ 0.  1. -0. -1.]
 [-1. -0.  1.  0.]
 [-0. -1.  0.  1.]]
( - 2 * (x(0,0) * x(1,0)) - 2 * (x(0,1) * x(1,1)) + pow(x(0,0), 2) + pow(x(1,0), 2) + pow(x(0,1), 2) + pow(x(1,1), 2))
